config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/articles' => 'articles#index'
  get '/articles/new' => 'articles#new', as: 'new_article'
  post '/articles' => 'articles#create', as: 'create_article'
  get '/articles/show/:id' => 'articles#show', as: 'show_article'
  get '/articles/edit/:id' => 'articles#edit', as: 'edit_article'
  put '/articles/update' => 'articles#update', as: 'update_article'
  delete '/articles/delete/:id' => 'articles#delete', as: 'delete_article'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true,
                      uniqueness: true
    validates :body,  presence: true,
                      length: { minimum: 100 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        @articles = Article.all
    end

    def show
        @article = Article.find(params[:id])  
    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)
        # @article.title = params[:article][:title]
        # @article.body = params[:article][:body]
        if @article.save
            redirect_to articles_path
        else
            render :new
        end
    end

    def edit
        @article = Article.find(params[:id])        
    end

    def update
        @article = Article.find(params[:article][:id])  
        if @article.update(article_params)
            redirect_to articles_path
        else
            render :edit
        end
    end

    def delete
        @article = Article.find(params[:id])  
        if @article.destroy
            redirect_to articles_path
        else
            render :edit
        end
    end

    private
    #strong parameter
    def article_params
        params.require(:article).permit(:title, :body)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<h1 class="title">Rails Blog > Edit</h1>
<div class="section">
    <%= form_with scope: :article, url: update_article_path, local: true, method: :put do |f|  %>
        <div class="validations">
            <% if @article.errors.any?  %>
                    <% @article.errors.full_messages.each do |message| %>
                        <div>
                            <%= message %>
                        </div>
                    <% end %>
            <% end %>     
        </div>
        <%= f.hidden_field :id %>
        <div class="form-group">
            <%= f.label :title, class: 'form-label' %>
            <%= f.text_field :title, class: 'text-input' %>
        </div>
        <div class="form-group">
            <%= f.label :body, class: 'form-label' %>
            <%= f.text_area :body, class: 'text-area' %>
        </div>

        <div class="form-group">
            <%= f.submit 'Save', class: 'button' %>
            <%=  link_to 'Delete', delete_article_path(@article.id), method: :delete, class: 'button', data: {confirm: "Are you sure you want to delete this article?"} %>
            <%=  link_to 'Cancel', articles_path, method: :get, class: 'button' %>
        </div>
    <% end %>
</div>

app/views/articles/index.html.erb
<h1 class="title">Rails Blog</h1>

<div class="section">
    <div class="articles-list">
        <div>
            <%= link_to '+ New Article', new_article_path, method: :get, class: 'button'%>
        </div>

        <% @articles.each do |article| %>
            <div class="list-article-item">
                <h3><%= link_to article.title, show_article_path(article.id), class: 'list-article-title' %></h3>
                <p class="list-article-body">
                    <%= article.body %>
                </p>

                <%= link_to 'View', show_article_path(article.id), method: :get, class: 'button' %>           
                <%= link_to 'Edit', edit_article_path(article.id), method: :get, class: 'button' %>           
            </div>
        <% end %>
    </div>
</div>

app/views/articles/new.html.erb
<h1 class="title">Rails Blog > Create</h1>
<div class="section">
    <%= form_with scope: :article, url: create_article_path, local: true do |f|  %>
        <div class="validations">
            <% if @article.errors.any?  %>
                    <% @article.errors.full_messages.each do |message| %>
                        <div>
                            <%= message %>
                        </div>
                    <% end %>
            <% end %>     
        </div>
        <div class="form-group">
            <%= f.label :title, class: 'form-label' %>
            <%= f.text_field :title, class: 'text-input' %>
        </div>
        <div class="form-group">
            <%= f.label :body, class: 'form-label' %>
            <%= f.text_area :body, class: 'text-area' %>
        </div>

        <div class="form-group">
            <%= f.submit 'Create', class: 'button' %>
            <%=  link_to 'Cancel', articles_path, method: :get, class: 'button' %>
        </div>
    <% end %>
</div>

app/views/articles/show.html.erb
<h1 class="title">Rails Blog > View</h1>


<div class="section">
    <h3 class="view-title"><%= @article.title %></h3>
    <p class="view-body"><%= @article.body %></p>
    <%=  link_to 'Back to Articles', articles_path, method: :get, class: 'button' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog Articles</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container"><%= yield %></div>
  </body>
</html>